/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f0f3ff',
        'tertiary-container': '#5ceaae',
        'on-tertiary-fixed': '#002113',
        'primary-container': '#00f090',
        'on-primary-fixed': '#00210f',
        'primary-fixed-dim': '#00e388',
        'on-primary-container': '#00683b',
        'tertiary-fixed-dim': '#4edea3',
        surface: '#f9f9ff',
        'on-primary': '#ffffff',
        secondary: '#5e5e63',
        'on-surface-variant': '#3b4a3f',
        'error-container': '#ffdad6',
        'outline-variant': '#bacbbc',
        'inverse-primary': '#00e388',
        'on-tertiary-fixed-variant': '#005236',
        'on-background': '#161c26',
        'secondary-container': '#e0dfe5',
        'on-secondary-fixed-variant': '#46464b',
        'primary-fixed': '#58ffa5',
        'surface-container-high': '#e3e8f7',
        'secondary-fixed-dim': '#c7c6cb',
        'on-secondary': '#ffffff',
        'surface-dim': '#d4dae9',
        'on-error-container': '#93000a',
        outline: '#6b7b6e',
        'surface-container-highest': '#dde2f1',
        'on-secondary-fixed': '#1a1b20',
        'on-tertiary': '#ffffff',
        'surface-container': '#e8eefd',
        'on-surface': '#161c26',
        'surface-variant': '#dde2f1',
        'tertiary-fixed': '#6ffbbe',
        'secondary-fixed': '#e3e2e7',
        'on-primary-fixed-variant': '#00522e',
        'inverse-on-surface': '#ecf1ff',
        'on-error': '#ffffff',
        'surface-bright': '#f9f9ff',
        tertiary: '#006c49',
        'on-secondary-container': '#626267',
        background: '#f9f9ff',
        'on-tertiary-container': '#006746',
        error: '#ba1a1a',
        'inverse-surface': '#2b313c',
        'surface-tint': '#006d3e',
        primary: '#006d3e',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'gutter-sm': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
        gutter: '1.5rem',
        margin: '4rem',
        'space-xs': '0.25rem',
        'margin-mobile': '1.5rem',
      },
      fontFamily: {
        'display-xl-mobile': ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
        'body-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'label-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'label-md': ['Plus Jakarta Sans', 'sans-serif'],
        'display-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
        'display-xl': ['Plus Jakarta Sans', 'sans-serif'],
        'display-lg-mobile': ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'display-xl-mobile': [
          '38px',
          {
            lineHeight: '44px',
            letterSpacing: '-0.02em',
            fontWeight: '800',
          },
        ],
        'body-lg': [
          '18px',
          {
            lineHeight: '28px',
            letterSpacing: '-0.005em',
            fontWeight: '400',
          },
        ],
        'headline-sm': [
          '20px',
          {
            lineHeight: '28px',
            letterSpacing: '-0.01em',
            fontWeight: '600',
          },
        ],
        'headline-md': [
          '28px',
          {
            lineHeight: '36px',
            letterSpacing: '-0.015em',
            fontWeight: '700',
          },
        ],
        'body-sm': [
          '13px',
          {
            lineHeight: '20px',
            letterSpacing: '0em',
            fontWeight: '500',
          },
        ],
        'label-sm': [
          '12px',
          {
            lineHeight: '16px',
            letterSpacing: '0.02em',
            fontWeight: '600',
          },
        ],
        'label-md': [
          '14px',
          {
            lineHeight: '18px',
            letterSpacing: '0.01em',
            fontWeight: '600',
          },
        ],
        'display-lg': [
          '48px',
          {
            lineHeight: '56px',
            letterSpacing: '-0.02em',
            fontWeight: '700',
          },
        ],
        'body-md': [
          '15px',
          {
            lineHeight: '24px',
            letterSpacing: '0em',
            fontWeight: '400',
          },
        ],
        'display-xl': [
          '64px',
          {
            lineHeight: '72px',
            letterSpacing: '-0.03em',
            fontWeight: '800',
          },
        ],
        'display-lg-mobile': [
          '32px',
          {
            lineHeight: '38px',
            letterSpacing: '-0.02em',
            fontWeight: '700',
          },
        ],
      },
    },
  },
  plugins: [],
};
